const ProvincesData = {
HANOI: {
    name: "Hanoi",
    cities: {
      QUANBADINH: "Ba Dinh District",
      QUANHOANKIEM: "Hoan Kiem District",
      QUANHAIBATRUNG: "Hai Ba Trung District",
      QUANDONGDA: "Dong Da District",
      QUANTAYHO: "Tay Ho District",
      QUANCAUGIAY: "Cau Giay District",
      QUANTHANHXUAN: "Thanh Xuan District",
      QUANHOANGMAI: "Hoang Mai District",
      QUANLONGBIEN: "Long Bien District",
      HUYENTULIEM: "Tu Liem District",
      HUYENTHANHTRI: "Thanh Tri District",
      HUYENGIALAM: "Gia Lam District",
      HUYENDONGANH: "Dong Anh District",
      HUYENSOCSON: "Soc Son District",
      QUANHADONG: "Ha Dong District",
      THIXASONTAY: "Son Tay Town",
      HUYENBAVI: "Ba Vi District",
      HUYENPHUCTHO: "Phuc Tho District",
      HUYENTHACHTHAT: "Thach That District",
      HUYENQUOCOAI: "Quoc Oai District",
      HUYENCHUONGMY: "Chuong My District",
      HUYENDANPHUONG: "Dan Phuong District",
      HUYENHOAIDUC: "Hoai Duc District",
      HUYENTHANHOAI: "Thanh Oai District",
      HUYENMYDUC: "My Duc District",
      HUYENUNGHOA: "Ung Hoa District",
      HUYENTHUONGTIN: "Thuong Tin District",
      HUYENPHUXUYEN: "Phu Xuyen District",
      HUYENMELINH: "Me Linh District",
      HANOIKHAC: "Other District",
    },
  },
HOCHIMINH: {
    name: "Ho Chi Minh City",
    cities: {
      QUAN1: "District 1",
      QUAN2: "District 2",
      QUAN3: "District 3",
      QUAN4: "District 4",
      QUAN5: "District 5",
      QUAN6: "District 6",
      QUAN7: "District 7",
      QUAN8: "District 8",
      QUAN9: "District 9",
      QUAN10: "District 10",
      QUAN11: "District 11",
      QUAN12: "District 12",
      QUANGOVAP: "Go Vap District",
      QUANTANBINH: "Tan Binh District",
      QUANTANPHU: "Tan Phu District",
      QUANBINHTHANH: "Binh Thanh District",
      QUANPHUNHUAN: "Phu Nhuan District",
      QUANTHUDUC: "Thu Duc District",
      QUANBINHTAN: "Binh Tan District",
      HUYENBINHCHANH: "Binh Chanh District",
      HUYENCUCHI: "Cu Chi District",
      HUYENHOCMON: "Hoc Mon District",
      HUYENNHABE: "Nha Be District",
      HUYENCANGIO: "Can Gio District",
      HOCHIMINHKHAC: "Other District",
    },
  },
HAIPHONG: {
    name: "Haiphong",
    cities: {
      QUANHONGBANG: "Hong Bang District",
      QUANLECHAN: "Le Chan District",
      QUANNGOQUYEN: "Ngo Quyen District",
      QUANKIENAN: "Kien An District",
      QUANHAIAN: "Hai An District",
      QUANDOSON: "Do Son District",
      HUYENANLAO: "An Lao District",
      HUYENKIENTHUY: "Kien Thuy District",
      HUYENTHUYNGUYEN: "Thuy Nguyen District",
      HUYENANDUONG: "An Duong District",
      HUYENTIENLANG: "Tien Lang District",
      HUYENVINHBAO: "Vinh Bao District",
      HUYENCATHAI: "Cat Hai District",
      HUYENBACHLONGVI: "Bach Long Vi District",
      QUANDUONGKINH: "Duong Kinh District",
      HAIPHONGKHAC: "Other District",
    },
  },
  DANANG: {
    name: "Da Nang",
    cities: {
      QUANHAICHAU: "Hai Chau District",
      QUANTHANHKHE: "Thanh Khe District",
      QUANSONTRA: "Son Tra District",
      QUANNGUHANHSON: "Ngu Hanh Son District",
      QUANLIENCHIEU: "Lien Chieu District",
      HUYENHOAVANG: "Hoa Vang District",
      QUANCAMLE: "Cam Le District",
      DANANGKHAC: "Other District",
    },
  },
HAGIANG: {
    name: "Ha Giang Province",
    cities: {
      THANHPHOHAGIANG: "Ha Giang City",
      HUYENDONGVAN: "Dong Van District",
      HUYENMEOVAC: "Meo Vac District",
      HUYENYENMINH: "Yen Minh District",
      HUYENQUANBA: "Quan Ba District",
      HUYENVIXUYEN: "Vi Xuyen District",
      HUYENBACME: "Bac Me District",
      HUYENHOANGSUPHI: "Hoang Su Phi District",
      HUYENXINMAN: "Xin Man District",
      HUYENBACQUANG: "Bac Quang District",
      HUYENQUANGBINH: "Quang Binh District",
      HAGIANGKHAC: "Other District",
    },
  },
  CAOBANG: {
    name: "Cao Bang Province",
    cities: {
      THANHPHOCAOBANG: "Cao Bang City",
      HUYENBAOLAC: "Bao Lac District",
      HUYENTHONGNONG: "Thong Nong District",
      HUYENHAQUANG: "Ha Quang District",
      HUYENTRALINH: "Tra Linh District",
      HUYENTRUNGKHANH: "Trung Khanh District",
      HUYENNGUYENBINH: "Nguyen Binh District",
      HUYENHOAAN: "Hoa An District",
      HUYENQUANGUYEN: "Quang Uyen District",
      HUYENTHACHAN: "Thach An District",
      HUYENHALANG: "Ha Lang District",
      HUYENBAOLAM: "Bao Lam District",
      HUYENPHUCHOA: "Phuc Hoa District",
      CAOBANGKHAC: "Other District",
    },
  },
LAICHAU: {
    name: "Lai Chau Province",
    cities: {
      THANHPHOLAICHAU: "Lai Chau City",
      HUYENTAMDUONG: "Tam Duong District",
      HUYENPHONGTHO: "Phong Tho District",
      HUYENSINHO: "Sin Ho District",
      HUYENMUONGTE: "Muong Te District",
      HUYENTHANUYEN: "Than Uyen District",
      HUYENTANUYEN: "Tan Uyen District",
      HUYENNAMNHUM: "Nam Nhun District",
      LAICHAUKHAC: "Other District",
    },
  },
  LAOCAI: {
    name: "Lao Cai Province",
    cities: {
      THANHPHOLAOCAI: "Lao Cai City",
      HUYENXIMACAI: "Xi Ma Cai District",
      HUYENBATXAT: "Bat Xat District",
      HUYENBAOTHANG: "Bao Thang District",
      HUYENSAPA: "Sa Pa District",
      HUYENVANBAN: "Van Ban District",
      HUYENBAOYEN: "Bao Yen District",
      HUYENBACHA: "Bac Ha District",
      HUYENMUONGKHUONG: "Muong Khuong District",
      LAOCAIKHAC: "Other District",
    },
  },
  TUYENQUANG: {
    name: "Tuyen Quang Province",
    cities: {
      "TH.PHOTUYENQUANG": "Tuyen Quang City",
      HUYENLAMBINH: "Lam Binh District",
      HUYENNAHANG: "Na Hang District",
      HUYENCHIEMHOA: "Chiem Hoa District",
      HUYENHAMYEN: "Ham Yen District",
      HUYENYENSON: "Yen Son District",
      HUYENSONDUONG: "Son Duong District",
      TUYENQUANGKHAC: "Other District",
    },
  },
  LANGSON: {
    name: "Lang Son Province",
    cities: {
      THANHPHOLANGSON: "Lang Son City",
      HUYENTRANGDINH: "Trang Dinh District",
      HUYENBINHGIA: "Binh Gia District",
      HUYENVANLANG: "Van Lang District",
      HUYENBACSON: "Bac Son District",
      HUYENVANQUAN: "Van Quan District",
      HUYENCAOLOC: "Cao Loc District",
      HUYENLOCBINH: "Loc Binh District",
      HUYENCHILANG: "Chi Lang District",
      HUYENDINHLAP: "Dinh Lap District",
      HUYENHUULUNG: "Huu Lung District",
      LANGSONKHAC: "Other District",
    },
  },
BACKAN: {
    name: "Bac Kan Province",
    cities: {
      THIXABACKAN: "Bac Kan Town",
      HUYENCHODON: "Cho Don District",
      HUYENBACHTHONG: "Bach Thong District",
      HUYENNARI: "Na Ri District",
      HUYENNGANSON: "Ngan Son District",
      HUYENBABE: "Ba Be District",
      HUYENCHOMOI: "Cho Moi District",
      HUYENPACNAM: "Pac Nam District",
      BACKANKHAC: "Other District",
    },
  },
  THAINGUYEN: {
    name: "Thai Nguyen Province",
    cities: {
      THANHPHOTHAINGUYEN: "Thai Nguyen City",
      THIXASONGCONG: "Song Cong Town",
      HUYENDINHHOA: "Dinh Hoa District",
      HUYENPHULUONG: "Phu Luong District",
      HUYENVONHAI: "Vo Nhai District",
      HUYENDAITU: "Dai Tu District",
      HUYENDONGHY: "Dong Hy District",
      HUYENPHUBINH: "Phu Binh District",
      HUYENPHOYEN: "Pho Yen District",
      THAINGUYENKHAC: "Other District",
    },
  },
  YENBAI: {
    name: "Yen Bai Province",
    cities: {
      THANHPHOYENBAI: "Yen Bai City",
      THIXANGHIALO: "Nghia Lo Town",
      HUYENVANYEN: "Van Yen District",
      HUYENYENBINH: "Yen Binh District",
      HUYENMUCANGCHAI: "Mu Cang Chai District",
      HUYENVANCHAN: "Van Chan District",
      HUYENTRANYEN: "Tran Yen District",
      HUYENTRAMTAU: "Tram Tau District",
      HUYENLUCYEN: "Luc Yen District",
      YENBAIKHAC: "Other District",
    },
  },
  SONLA: {
    name: "Son La Province",
    cities: {
      THANHPHOSONLA: "Son La City",
      HUYENQUYNHNHAI: "Quynh Nhai District",
      HUYENMUONGLA: "Muong La District",
      HUYENTHUANCHAU: "Thuan Chau District",
      HUYENBACYEN: "Bac Yen District",
      HUYENPHUYEN: "Phu Yen District",
      HUYENMAISON: "Mai Son District",
      HUYENYENCHAU: "Yen Chau District",
      HUYENSONGMA: "Song Ma District",
      HUYENMOCCHAU: "Moc Chau District",
      HUYENSOPCOP: "Sop Cop District",
      HUYENVANHO: "Van Ho District",
      SONLAKHAC: "Other District",
    },
  },
  PHUTHO: {
    name: "Phu Tho Province",
    cities: {
      THANHPHOVIETTRI: "Viet Tri City",
      THIXAPHUTHO: "Phu Tho Town",
      HUYENDOANHUNG: "Doan Hung District",
      HUYENTHANHBA: "Thanh Ba District",
      HUYENHAHOA: "Ha Hoa District",
      HUYENCAMKHE: "Cam Khe District",
      HUYENYENLAP: "Yen Lap District",
      HUYENTHANHSON: "Thanh Son District",
      HUYENPHUNINH: "Phu Ninh District",
      HUYENLAMTHAO: "Lam Thao District",
      HUYENTAMNONG: "Tam Nong District",
      HUYENTHANHTHUY: "Thanh Thuy District",
      HUYENTANSON: "Tan Son District",
      PHUTHOKHAC: "Other District",
    },
  },
  VINHPHUC: {
    name: "Vinh Phuc Province",
    cities: {
      THANHPHOVINHYEN: "Vinh Yen City",
      HUYENTAMDUONG: "Tam Duong District",
      HUYENLAPTHACH: "Lap Thach District",
      HUYENVINHTUONG: "Vinh Tuong District",
      HUYENYENLAC: "Yen Lac District",
      HUYENBINHXUYEN: "Binh Xuyen District",
      HUYENSONGLO: "Song Lo District",
      THIXAPHUCYEN: "Phuc Yen Town",
      HUYENTAMDAO: "Tam Dao District",
      VINHPHUCKHAC: "Other District",
    },
  }

};

const provinces = Object.values(ProvincesData);

export default provinces;
